=== EV081/Rimac-HCKT/DataGenerator/schemas-validation/memoria_contextual.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Memoria Contextual",
    "type": "object",
    "x-dynamodb": {
        "partition_key": "correo",
        "sort_key": "context_id"
    },
    "properties": {
        "correo": {
            "type": "string",
            "format": "email"
        },
        "context_id": {
            "type": "string"
        },
        "fecha": {
            "type": "string",
            "format": "date-time"
        },
        "resumen_conversacion": {
            "type": "string"
        },
        "intencion_detectada": {
            "type": "string"
        },
        "datos_extraidos": {
            "type": "object",
            "additionalProperties": true
        }
    },
    "required": [
        "correo",
        "context_id",
        "fecha",
        "resumen_conversacion"
    ],
    "additionalProperties": false
}

=== EV081/Rimac-HCKT/DataGenerator/example-data/memoria_contextual.json
[
  {
    "correo": "autoridad@utec.edu.pe",
    "context_id": "ctx-80855b69",
    "fecha": "2025-10-29T20:57:13.111261",
    "resumen_conversacion": "El usuario consultó sobre estrés y se le recomendó mejorar sus hábitos.",
    "intencion_detectada": "registrar",
    "datos_extraidos": {
      "tema_principal": "estrés",
      "sentimiento": "neutral",
      "urgencia": "alta"
    }
  },
  {
    "correo": "autoridad@utec.edu.pe",
    "context_id": "ctx-b59273f6",
    "fecha": "2025-11-12T19:57:13.111303",
    "resumen_conversacion": "El usuario consultó sobre ejercicio y se le recomendó mejorar sus hábitos.",
    "intencion_detectada": "pedir consejo",
    "datos_extraidos": {
      "tema_principal": "ejercicio",
      "sentimiento": "neutral",
      "urgencia": "alta"
    }
  },
  {
    "correo": "autoridad@utec.edu.pe",
    "context_id": "ctx-453ed705",
    "fecha": "2025-11-22T10:57:13.111313",
    "resumen_conversacion": "El usuario consultó sobre ejercicio y se le recomendó mejorar sus hábitos.",
    "intencion_detectada": "quejarse",
    "datos_extraidos": {
      "tema_principal": "ejercicio",
      "sentimiento": "negativo",
      "urgencia": "media"
    }
  },
  {
    "correo": "fernando.vega@gmail.com",
    "context_id": "ctx-60eb57f2",
    "fecha": "2025-11-22T05:57:13.111322",
    "resumen_conversacion": "El usuario consultó sobre ejercicio y se le recomendó mejorar sus hábitos.",
    "intencion_detectada": "consultar",
    "datos_extraidos": {
      "tema_principal": "ejercicio",
      "sentimiento": "neutral",
      "urgencia": "media"
    }
  },
  {
    "correo": "fernando.vega@gmail.com",
    "context_id": "ctx-59bb1e2b",
    "fecha": "2025-10-26T18:57:13.111328",
    "resumen_conversacion": "El usuario consultó sobre estrés y se le recomendó mejorar sus hábitos.",
    "intencion_detectada": "pedir consejo",
    "datos_extraidos": {
      "tema_principal": "estrés",
      "sentimiento": "neutral",
      "urgencia": "media"
    }
  },
  {
    "correo": "fernando.vega@gmail.com",
    "context_id": "ctx-c42b18c6",
    "fecha": "2025-11-10T15:57:13.111333",
    "resumen_conversacion": "El usuario consultó sobre ejercicio y se le recomendó mejorar sus hábitos.",
    "intencion_detectada": "registrar",
    "datos_extraidos": {
      "tema_principal": "ejercicio",
      "sentimiento": "negativo",
      "urgencia": "baja"
    }
  },
  {
    "correo": "fernando.vega@gmail.com",
    "context_id": "ctx-f763db75",
    "fecha": "2025-11-08T04:57:13.111339",
    "resumen_conversacion": "El usuario consultó sobre ejercicio y se le recomendó mejorar sus hábitos.",
    "intencion_detectada": "pedir consejo",
    "datos_extraidos": {
      "tema_principal": "ejercicio",
      "sentimiento": "negativo",
      "urgencia": "baja"
    }
  },
  {
    "correo": "patricia.ruiz@gmail.com",
    "context_id": "ctx-8300d999",
    "fecha": "2025-11-08T15:57:13.111344",
    "resumen_conversacion": "El usuario consultó sobre sueño y se le recomendó mejorar sus hábitos.",
    "intencion_detectada": "pedir consejo",
    "datos_extraidos": {
      "tema_principal": "sueño",
      "sentimiento": "negativo",
      "urgencia": "media",
      "horas_promedio": 7
    }
  },
  {
    "correo": "patricia.ruiz@gmail.com",
    "context_id": "ctx-9ac66219",
    "fecha": "2025-11-01T13:57:13.111350",
    "resumen_conversacion": "El usuario consultó sobre nutrición y se le recomendó mejorar sus hábitos.",
    "intencion_detectada": "consultar",
    "datos_extraidos": {
      "tema_principal": "nutrición",
      "sentimiento": "positivo",
      "urgencia": "media",
      "preferencia_alimenticia": "keto"
    }
  },
  {
    "correo": "carlos.lópez@gmail.com",
    "context_id": "ctx-67ffa57e",
    "fecha": "2025-11-23T02:57:13.111355",
    "resumen_conversacion": "El usuario consultó sobre ejercicio y se le recomendó mejorar sus hábitos.",
    "intencion_detectada": "consultar",
    "datos_extraidos": {
      "tema_principal": "ejercicio",
      "sentimiento": "neutral",
      "urgencia": "alta"
    }
  },
  {
    "correo": "carlos.lópez@gmail.com",
    "context_id": "ctx-d341a418",
    "fecha": "2025-10-31T13:57:13.111360",
    "resumen_conversacion": "El usuario consultó sobre sueño y se le recomendó mejorar sus hábitos.",
    "intencion_detectada": "registrar",
    "datos_extraidos": {
      "tema_principal": "sueño",
      "sentimiento": "positivo",
      "urgencia": "media",
      "horas_promedio": 4
    }
  },
  {
    "correo": "carlos.lópez@gmail.com",
    "context_id": "ctx-9381e848",
    "fecha": "2025-11-04T19:57:13.111365",
    "resumen_conversacion": "El usuario consultó sobre medicación y se le recomendó mejorar sus hábitos.",
    "intencion_detectada": "pedir consejo",
    "datos_extraidos": {
      "tema_principal": "medicación",
      "sentimiento": "negativo",
      "urgencia": "media"
    }
  },
  {
    "correo": "carlos.lópez@gmail.com",
    "context_id": "ctx-51526e2c",
    "fecha": "2025-11-22T02:57:13.111369",
    "resumen_conversacion": "El usuario consultó sobre ejercicio y se le recomendó mejorar sus hábitos.",
    "intencion_detectada": "consultar",
    "datos_extraidos": {
      "tema_principal": "ejercicio",
      "sentimiento": "neutral",
      "urgencia": "alta"
    }
  },
  {
    "correo": "carlos.lópez@utec.edu.pe",
    "context_id": "ctx-ce533376",
    "fecha": "2025-10-25T07:57:13.111374",
    "resumen_conversacion": "El usuario consultó sobre medicación y se le recomendó mejorar sus hábitos.",
    "intencion_detectada": "quejarse",
    "datos_extraidos": {
      "tema_principal": "medicación",
      "sentimiento": "positivo",
      "urgencia": "baja"
    }
  },
  {
    "correo": "carlos.lópez@utec.edu.pe",
    "context_id": "ctx-b089eabc",
    "fecha": "2025-11-09T18:57:13.111378",
    "resumen_conversacion": "El usuario consultó sobre ejercicio y se le recomendó mejorar sus hábitos.",
    "intencion_detectada": "pedir consejo",
    "datos_extraidos": {
      "tema_principal": "ejercicio",
      "sentimiento": "neutral",
      "urgencia": "baja"
    }
  },
  {
    "correo": "luis.rodríguez@outlook.com",
    "context_id": "ctx-f746d8a4",
    "fecha": "2025-10-29T22:57:13.111383",
    "resumen_conversacion": "El usuario consultó sobre nutrición y se le recomendó mejorar sus hábitos.",
    "intencion_detectada": "consultar",
    "datos_extraidos": {
      "tema_principal": "nutrición",
      "sentimiento": "neutral",
      "urgencia": "media",
      "preferencia_alimenticia": "vegetariano"
    }
  },
  {
    "correo": "luis.rodríguez@outlook.com",
    "context_id": "ctx-88cad01a",
    "fecha": "2025-11-02T13:57:13.111388",
    "resumen_conversacion": "El usuario consultó sobre nutrición y se le recomendó mejorar sus hábitos.",
    "intencion_detectada": "pedir consejo",
    "datos_extraidos": {
      "tema_principal": "nutrición",
      "sentimiento": "neutral",
      "urgencia": "alta",
      "preferencia_alimenticia": "omnívoro"
    }
  },
  {
    "correo": "luis.rodríguez@outlook.com",
    "context_id": "ctx-ce81caac",
    "fecha": "2025-10-23T08:57:13.111394",
    "resumen_conversacion": "El usuario consultó sobre medicación y se le recomendó mejorar sus hábitos.",
    "intencion_detectada": "quejarse",
    "datos_extraidos": {
      "tema_principal": "medicación",
      "sentimiento": "positivo",
      "urgencia": "alta"
    }
  },
  {
    "correo": "luis.rodríguez@outlook.com",
    "context_id": "ctx-c3067bab",
    "fecha": "2025-11-17T02:57:13.111398",
    "resumen_conversacion": "El usuario consultó sobre nutrición y se le recomendó mejorar sus hábitos.",
    "intencion_detectada": "consultar",
    "datos_extraidos": {
      "tema_principal": "nutrición",
      "sentimiento": "neutral",
      "urgencia": "baja",
      "preferencia_alimenticia": "vegetariano"
    }
  },
  {
    "correo": "pedro.flores@utec.edu.pe",
    "context_id": "ctx-19f4b252",
    "fecha": "2025-11-07T13:57:13.111403",
    "resumen_conversacion": "El usuario consultó sobre estrés y se le recomendó mejorar sus hábitos.",
    "intencion_detectada": "quejarse",
    "datos_extraidos": {
      "tema_principal": "estrés",
      "sentimiento": "negativo",
      "urgencia": "baja"
    }
  },
  {
    "correo": "pedro.flores@utec.edu.pe",
    "context_id": "ctx-6ed3c0c3",
    "fecha": "2025-11-01T00:57:13.111407",
    "resumen_conversacion": "El usuario consultó sobre ejercicio y se le recomendó mejorar sus hábitos.",
    "intencion_detectada": "consultar",
    "datos_extraidos": {
      "tema_principal": "ejercicio",
      "sentimiento": "positivo",
      "urgencia": "baja"
    }
  },
  {
    "correo": "pedro.flores@utec.edu.pe",
    "context_id": "ctx-1ec3dfa0",
    "fecha": "2025-10-28T06:57:13.111412",
    "resumen_conversacion": "El usuario consultó sobre sueño y se le recomendó mejorar sus hábitos.",
    "intencion_detectada": "registrar",
    "datos_extraidos": {
      "tema_principal": "sueño",
      "sentimiento": "negativo",
      "urgencia": "baja",
      "horas_promedio": 4
    }
  },
  {
    "correo": "pedro.flores@utec.edu.pe",
    "context_id": "ctx-0008a3f7",
    "fecha": "2025-11-16T22:57:13.111418",
    "resumen_conversacion": "El usuario consultó sobre sueño y se le recomendó mejorar sus hábitos.",
    "intencion_detectada": "consultar",
    "datos_extraidos": {
      "tema_principal": "sueño",
      "sentimiento": "neutral",
      "urgencia": "alta",
      "horas_promedio": 6
    }
  },
  {
    "correo": "isabel.ramírez@utec.edu.pe",
    "context_id": "ctx-5c770ecb",
    "fecha": "2025-10-24T16:57:13.111426",
    "resumen_conversacion": "El usuario consultó sobre nutrición y se le recomendó mejorar sus hábitos.",
    "intencion_detectada": "pedir consejo",
    "datos_extraidos": {
      "tema_principal": "nutrición",
      "sentimiento": "positivo",
      "urgencia": "alta",
      "preferencia_alimenticia": "omnívoro"
    }
  },
  {
    "correo": "isabel.ramírez@utec.edu.pe",
    "context_id": "ctx-92fc550d",
