=== EV081/Rimac-HCKT/DataGenerator/schemas-validation/recetas.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Recetas",
  "type": "object",
  "x-dynamodb": {
    "partition_key": "receta_id"
  },
  "properties": {
    "receta_id": {
      "type": "string"
    },
    "paciente": {
      "type": "string"
    },
    "institucion": {
      "type": "string"
    },
    "recetas": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "producto": {
            "type": "string"
          },
          "dosis": {
            "type": ["string", "null"]
          },
          "frecuencia": {
            "type": "integer"
          },
          "medicion_frecuencia": {
            "type": "string",
            "enum": ["dias", "horas", "meses"]
          },
          "duracion": {
            "type": "integer"
          },
          "duracion_frecuencia": {
            "type": "string",
            "enum": ["dias", "horas", "meses"]
          }
        },
        "required": ["producto", "frecuencia", "medicion_frecuencia", "duracion", "duracion_frecuencia"],
        "additionalProperties": false
      }
    }
  },
  "required": ["receta_id", "paciente", "institucion", "recetas"],
  "additionalProperties": false
}

=== EV081/Rimac-HCKT/DataGenerator/example-data/recetas.json
[
  {
    "receta_id": "rec-4711819d",
    "paciente": "Roberto Díaz",
    "institucion": "Centro Dermatológico \"Dr. Ladislao de la Pascua\"",
    "recetas": [
      {
        "producto": "Diclofenaco",
        "dosis": "75 mg",
        "frecuencia": 12,
        "medicion_frecuencia": "horas",
        "duracion": 5,
        "duracion_frecuencia": "dias"
      },
      {
        "producto": "Atorvastatina",
        "dosis": "20 mg",
        "frecuencia": 1,
        "medicion_frecuencia": "dias",
        "duracion": 6,
        "duracion_frecuencia": "meses"
      },
      {
        "producto": "Lagrifilm",
        "dosis": null,
        "frecuencia": 3,
        "medicion_frecuencia": "horas",
        "duracion": 1,
        "duracion_frecuencia": "meses"
      }
    ]
  },
  {
    "receta_id": "rec-46768819",
    "paciente": "Roberto Díaz",
    "institucion": "Centro Médico ABC",
    "recetas": [
      {
        "producto": "Amoxicilina",
        "dosis": "875 mg",
        "frecuencia": 12,
        "medicion_frecuencia": "horas",
        "duracion": 7,
        "duracion_frecuencia": "dias"
      }
    ]
  },
  {
    "receta_id": "rec-65d1d210",
    "paciente": "Carmen Fernández",
    "institucion": "Clínica Santa María",
    "recetas": [
      {
        "producto": "Vitamina D3",
        "dosis": "1000 UI",
        "frecuencia": 1,
        "medicion_frecuencia": "dias",
        "duracion": 3,
        "duracion_frecuencia": "meses"
      }
    ]
  },
  {
    "receta_id": "rec-3f57a9f8",
    "paciente": "Valentina Ortiz",
    "institucion": "Clínica Santa María",
    "recetas": [
      {
        "producto": "Clonazepam",
        "dosis": "0.5 mg",
        "frecuencia": 1,
        "medicion_frecuencia": "dias",
        "duracion": 2,
        "duracion_frecuencia": "meses"
      },
      {
        "producto": "Atorvastatina",
        "dosis": "20 mg",
        "frecuencia": 1,
        "medicion_frecuencia": "dias",
        "duracion": 6,
        "duracion_frecuencia": "meses"
      },
      {
        "producto": "Diclofenaco",
        "dosis": "75 mg",
        "frecuencia": 12,
        "medicion_frecuencia": "horas",
        "duracion": 5,
        "duracion_frecuencia": "dias"
      }
    ]
  },
  {
    "receta_id": "rec-0c0950ed",
    "paciente": "Valentina Ortiz",
    "institucion": "Hospital General de México",
    "recetas": [
      {
        "producto": "Diclofenaco",
        "dosis": "75 mg",
        "frecuencia": 12,
        "medicion_frecuencia": "horas",
        "duracion": 5,
        "duracion_frecuencia": "dias"
      },
      {
        "producto": "Vitamina D3",
        "dosis": "1000 UI",
        "frecuencia": 1,
        "medicion_frecuencia": "dias",
        "duracion": 3,
        "duracion_frecuencia": "meses"
      }
    ]
  },
  {
    "receta_id": "rec-f094e271",
    "paciente": "Fernando Vega",
    "institucion": "Hospital General de México",
    "recetas": [
      {
        "producto": "Amoxicilina",
        "dosis": "875 mg",
        "frecuencia": 12,
        "medicion_frecuencia": "horas",
        "duracion": 7,
        "duracion_frecuencia": "dias"
      },
      {
        "producto": "Vitamina D3",
        "dosis": "1000 UI",
        "frecuencia": 1,
        "medicion_frecuencia": "dias",
        "duracion": 3,
        "duracion_frecuencia": "meses"
      }
    ]
  },
  {
    "receta_id": "rec-5815e139",
    "paciente": "Sofía Castro",
    "institucion": "Hospital General de México",
    "recetas": [
      {
        "producto": "Ranitidina",
        "dosis": "150 mg",
        "frecuencia": 12,
        "medicion_frecuencia": "horas",
        "duracion": 30,
        "duracion_frecuencia": "dias"
      },
      {
        "producto": "nasalub",
        "dosis": null,
        "frecuencia": 2,
        "medicion_frecuencia": "horas",
        "duracion": 1,
        "duracion_frecuencia": "meses"
      },
      {
        "producto": "Paracetamol",
        "dosis": "500 mg",
        "frecuencia": 8,
        "medicion_frecuencia": "horas",
        "duracion": 5,
        "duracion_frecuencia": "dias"
      },
      {
        "producto": "Omeprazol",
        "dosis": "20 mg",
        "frecuencia": 1,
        "medicion_frecuencia": "dias",
        "duracion": 14,
        "duracion_frecuencia": "dias"
      }
    ]
  },
  {
    "receta_id": "rec-46d91131",
    "paciente": "Carmen Fernández",
    "institucion": "Instituto Nacional de Salud",
    "recetas": [
      {
        "producto": "Atorvastatina",
        "dosis": "20 mg",
        "frecuencia": 1,
        "medicion_frecuencia": "dias",
        "duracion": 6,
        "duracion_frecuencia": "meses"
      },
      {
        "producto": "Paracetamol",
        "dosis": "500 mg",
        "frecuencia": 8,
        "medicion_frecuencia": "horas",
        "duracion": 5,
        "duracion_frecuencia": "dias"
      }
    ]
  },
  {
    "receta_id": "rec-5533de4e",
    "paciente": "Magali Flores",
    "institucion": "Clínica Santa María",
    "recetas": [
      {
        "producto": "Metformina",
        "dosis": "850 mg",
        "frecuencia": 12,
        "medicion_frecuencia": "horas",
        "duracion": 3,
        "duracion_frecuencia": "meses"
      },
      {
        "producto": "Omeprazol",
        "dosis": "20 mg",
        "frecuencia": 1,
        "medicion_frecuencia": "dias",
        "duracion": 14,
        "duracion_frecuencia": "dias"
      },
      {
        "producto": "Ranitidina",
        "dosis": "150 mg",
        "frecuencia": 12,
        "medicion_frecuencia": "horas",
        "duracion": 30,
        "duracion_frecuencia": "dias"
      },
      {
        "producto": "Atorvastatina",
        "dosis": "20 mg",
        "frecuencia": 1,
        "medicion_frecuencia": "dias",
        "duracion": 6,
        "duracion_frecuencia": "meses"
      }
    ]
  },
  {
    "receta_id": "rec-93f6d629",
    "paciente": "José González",
    "institucion": "Clínica Santa María",
    "recetas": [
      {
        "producto": "Atorvastatina",
        "dosis": "20 mg",
        "frecuencia": 1,
        "medicion_frecuencia": "dias",
        "duracion": 6,
        "duracion_frecuencia": "meses"
      },
      {
        "producto": "Aspirina",
        "dosis": "100 mg",
        "frecuencia": 1,
        "medicion_frecuencia": "dias",
        "duracion": 1,
        "duracion_frecuencia": "meses"
      },
      {
        "producto": "Loratadina",
        "dosis": "10 mg",
        "frecuencia": 24,
        "medicion_frecuencia": "horas",
        "duracion": 10,
        "duracion_frecuencia": "dias"
      },
      {
        "producto": "Trevissage",
        "dosis": "20 mg",
        "frecuencia": 1,
        "medicion_frecuencia": "dias",
        "duracion": 2,
        "duracion_frecuencia": "meses"
      }
    ]
  }
]
