=== EV081/Rimac-HCKT/DataGenerator/schemas-validation/usuarios_dependientes.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Usuarios Dependientes",
  "type": "object",
  "x-dynamodb": {
    "partition_key": "correo_tutor",
    "sort_key": "dependiente_id"
  },
  "properties": {
    "correo_tutor": {
      "type": "string",
      "format": "email"
    },
    "dependiente_id": { "type": "string" },
    "nombre": { "type": "string" },
    "cumpleanos": { "type": "string" },
    "parentesco": { 
        "type": "string",
        "enum": ["HIJO", "ADULTO_MAYOR"]
    },
    "sexo": { 
        "type": "string",
        "enum": ["M", "F"]
    }
  },
  "required": ["correo_tutor", "nombre", "cumpleanos", "parentesco", "sexo"],
  "additionalProperties": false
}

=== EV081/Rimac-HCKT/DataGenerator/example-data/usuarios_dependientes.json
[
  {
    "correo_tutor": "autoridad@utec.edu.pe",
    "dependiente_id": "dep-8a88dc3f",
    "nombre": "Valentina",
    "cumpleanos": "1951-07-23",
    "parentesco": "ADULTO_MAYOR",
    "sexo": "F"
  },
  {
    "correo_tutor": "autoridad@utec.edu.pe",
    "dependiente_id": "dep-3625d3e8",
    "nombre": "Pedrito",
    "cumpleanos": "1963-09-22",
    "parentesco": "ADULTO_MAYOR",
    "sexo": "F"
  },
  {
    "correo_tutor": "autoridad@utec.edu.pe",
    "dependiente_id": "dep-13bba2e7",
    "nombre": "Joaqu√≠n",
    "cumpleanos": "2015-10-25",
    "parentesco": "HIJO",
    "sexo": "F"
  }
]
